// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGzXMf9d0jwmbum3SoiTJuvpOHBK74Zp0',
    appId: '1:408408873014:web:b2e90eed2e7da289dd6097',
    messagingSenderId: '408408873014',
    projectId: 'project-in-my-pocket-beta',
    authDomain: 'project-in-my-pocket-beta.firebaseapp.com',
    storageBucket: 'project-in-my-pocket-beta.firebasestorage.app',
    measurementId: 'G-97PJG1RKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpLZmz72FEYSntW3KXYprEx1GG6-xTM0',
    appId: '1:408408873014:android:8ee8cde9cbd1a3e4dd6097',
    messagingSenderId: '408408873014',
    projectId: 'project-in-my-pocket-beta',
    storageBucket: 'project-in-my-pocket-beta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgZAq2SS9_7wNo5ECHuDZkqQKR1eHcRo',
    appId: '1:408408873014:ios:5fe5682bd6acbc32dd6097',
    messagingSenderId: '408408873014',
    projectId: 'project-in-my-pocket-beta',
    storageBucket: 'project-in-my-pocket-beta.firebasestorage.app',
    iosBundleId: 'com.example.projectInMyPocketBetaVer1',
  );
}
