// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAckzj_7DMNgmj-ZgBKBqWUoC7s_ZMmDDw',
    appId: '1:1088859395818:web:de22fd3c5b59dd9c05a993',
    messagingSenderId: '1088859395818',
    projectId: 'pimp-b7075',
    authDomain: 'pimp-b7075.firebaseapp.com',
    storageBucket: 'pimp-b7075.firebasestorage.app',
    measurementId: 'G-FWV7YQ3D23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmOnEnA5Aqtuuk_jlt-Z8MBM5dEVW2GVI',
    appId: '1:1088859395818:android:d359b5c0be653e0705a993',
    messagingSenderId: '1088859395818',
    projectId: 'pimp-b7075',
    storageBucket: 'pimp-b7075.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xYWtjDJROXSl2BuOOLcqJOK9hyBs0_E',
    appId: '1:1088859395818:ios:9dd717026ee0922705a993',
    messagingSenderId: '1088859395818',
    projectId: 'pimp-b7075',
    storageBucket: 'pimp-b7075.firebasestorage.app',
    iosBundleId: 'com.example.projectInMyPocketBetaVer1',
  );
}
